Financial accounts overview + create new financial account
TIS2022-FMFI/personalaccount pull request #29
Opened 2022-12-21 13:20 UTC by jakloo

#12

2022-12-21 19:22 UTC, mousetom-sk requested changes
Please, stick to the convention of writing { on a new line in function and class definitions. Also try to use single quotes everywhere.

Side note: You always create new operation types during testing, which sometimes results in a unique constraint violation...at least on my machine (probably the faker does not work the way I expected).

2022-12-21 19:22 UTC, mousetom-sk commented on src/database/migrations/3_create_accounts_table.php
> +            $table->unsignedBigInteger('user_id')->unsigned();
```suggestion
            $table->unsignedBigInteger('user_id');
```

2022-12-21 19:22 UTC, mousetom-sk commented on src/database/migrations/5_create_financial_operations_table.php
> +            $table->foreign('operation_type_id')->references("id")->on("operation_types")
I would keep that in a single line.

2022-12-21 19:22 UTC, mousetom-sk commented on src/routes/web.php
> +    Route::post('/create_account', [FinancialAccountsOverviewController::class, 'createFinancialAccount'])
```suggestion
    Route::post('/create-account', [FinancialAccountsOverviewController::class, 'createFinancialAccount'])
```

2022-12-21 19:22 UTC, mousetom-sk commented on src/app/Http/Controllers/FinancialAccounts/FinancialAccountsOverviewController.php
> +        foreach ($accounts as $account){
This is a bit weird construct...I would change the definition of calculateBalance so that it returns the balance instead of storing it in a member property. In that case, no foreach cycle is needed here and you can directly write:

return view("finances.index", [ "accounts" => Auth::user()->accounts ]);

2022-12-21 19:22 UTC, mousetom-sk commented on src/app/Http/Controllers/FinancialAccounts/FinancialAccountsOverviewController.php
> +    public function createFinancialAccount(CreateFinancialAccountRequest $request){
In my view, this would look cleaner:
$user = Auth::user();
...
$account = $user->accounts()->create([ 'title' => $title, 'sap_id' => $sap_id ]);
...
if ($account->exists) {
...
}

2022-12-21 19:22 UTC, mousetom-sk commented on src/app/Http/Requests/FinancialAccounts/CreateFinancialAccountRequest.php
> +            'title' => ['required'],
```suggestion
            'title' => ['required', 'max:255'],
```

2022-12-21 19:22 UTC, mousetom-sk commented on src/app/Http/Requests/FinancialAccounts/CreateFinancialAccountRequest.php
> +            'sap_id' => ['required']
```suggestion
            'sap_id' => ['required', 'max:255']
```

2022-12-21 19:22 UTC, mousetom-sk commented on src/app/Models/FinancialOperation.php
> +
Add this to enable eager loading of operationType (and avoid N+1 select problem):
```suggestion
protected $with = ['operationType'];
```

2022-12-21 19:22 UTC, mousetom-sk commented on src/app/Models/OperationType.php
> +    public function financialOperations()
This is unnecessary for now...and I am not sure whether it will be needed in future, therefore; I would remove it.

2022-12-21 19:22 UTC, mousetom-sk commented on src/app/Models/User.php
> +        return $this->hasMany(Account::class)->with('financialOperations.operationType');
If I am not mistaken, this should be enough after adding the with property to FinancialOperation:
```suggestion
        return $this->hasMany(Account::class)->with('financialOperations');
```

2022-12-21 19:22 UTC, mousetom-sk commented on src/database/factories/FinancialOperationFactory.php
> +        return [
indentation...

2022-12-21 19:22 UTC, mousetom-sk commented on src/app/Providers/AuthServiceProvider.php
> +        Gate::define('open-account-detail', function (User $user, Account $account) {
You do not need to take care of authorization...that will be my job.

2022-12-21 19:22 UTC, mousetom-sk commented on src/app/Models/FinancialOperation.php
> +        return $this->operationType->expense == 1;
I think boolean casts are done automatically (speaking from my own experience):
```suggestion
        return $this->operationType->expense;
```

2022-12-22 08:14 UTC, jakloo commented on src/app/Models/User.php
> +        return $this->hasMany(Account::class)->with('financialOperations.operationType');
The same can be done for "with('financialOperations')" then, fully eliminating the 'with' clause from this command. There doesn't seem to be a situation where accounts should be fetched without their operations, so added the 'with' property to them as well.

2022-12-22 09:47 UTC, mousetom-sk requested changes

2022-12-22 09:47 UTC, mousetom-sk commented on src/app/Http/Controllers/FinancialAccounts/FinancialAccountsOverviewController.php
> +        if ($account->exists()) return response(trans('finance_accounts.new.success'), 201);
'exists' is just a property:
```suggestion
        if ($account->exists) return response(trans('finance_accounts.new.success'), 201);
```

2022-12-22 09:47 UTC, mousetom-sk commented on src/app/Models/Account.php
> +    protected $with = ['financialOperations'];
I think we should not eager load financialOperations.

2022-12-22 09:47 UTC, mousetom-sk commented on src/app/Models/Account.php
>      public function hasNegativeBalance(): bool
Is this method still necessary? I do not think so.

2022-12-22 09:47 UTC, mousetom-sk commented on src/app/Models/Account.php
>       *
Property 'balance' can be safely removed, I suppose.

2022-12-22 12:17 UTC, mousetom-sk requested changes
Hopefully the last remark: just add PHPDocs for scopeExpenses and scopeIncomes.

2022-12-22 12:50 UTC, mousetom-sk approved these changes

2022-12-22 12:50 UTC, merged